-- Инициализация локальной базы данных Layndaru (PostgreSQL)

-- 1. Таблица общежитий (dormitories)
CREATE TABLE IF NOT EXISTS dormitories (
    id SERIAL PRIMARY KEY,
    number INTEGER NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255)
);

-- 2. Таблица комнат (rooms)
CREATE TABLE IF NOT EXISTS rooms (
    idroom INTEGER PRIMARY KEY
);

-- 3. Таблица жителей (residents)
CREATE TABLE IF NOT EXISTS residents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_id BIGINT,
    vk_id BIGINT,
    max_id BIGINT,
    language TEXT DEFAULT 'RU',
    dormitory_id INTEGER REFERENCES dormitories(id) ON DELETE SET NULL DEFAULT 1,
    inidroom INTEGER REFERENCES rooms(idroom) ON DELETE SET NULL,
    idcards VARCHAR(50) UNIQUE,
    last_name VARCHAR(100),
    first_name VARCHAR(100),
    patronymic VARCHAR(100),
    notify_unconfirmed BOOLEAN NOT NULL DEFAULT true,
    is_banned BOOLEAN NOT NULL DEFAULT false,
    score INTEGER NOT NULL DEFAULT 100,
    confirm_streak INTEGER NOT NULL DEFAULT 0,
    miss_streak INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_residents_tg_id ON residents(tg_id);
CREATE INDEX IF NOT EXISTS idx_residents_vk_id ON residents(vk_id);
CREATE INDEX IF NOT EXISTS idx_residents_max_id ON residents(max_id);
CREATE INDEX IF NOT EXISTS idx_residents_dormitory ON residents(dormitory_id);
CREATE INDEX IF NOT EXISTS idx_residents_idcards ON residents(idcards);
CREATE INDEX IF NOT EXISTS idx_residents_fio ON residents(last_name, first_name);
CREATE INDEX IF NOT EXISTS idx_residents_score ON residents(score);

-- 3.1. Журнал баллов дисциплины (resident_score_logs)
CREATE TABLE IF NOT EXISTS resident_score_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resident_id BIGINT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
    booking_id BIGINT REFERENCES booking(id) ON DELETE SET NULL,
    delta INTEGER NOT NULL,
    score_after INTEGER NOT NULL,
    reason VARCHAR(50) NOT NULL,
    details TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_score_logs_resident ON resident_score_logs(resident_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_score_logs_booking ON resident_score_logs(booking_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_score_logs_booking_reason ON resident_score_logs(booking_id, reason);

-- 4. Таблица машин (machines)
-- status: 1 = Работает, 0 = Отключена
CREATE TABLE IF NOT EXISTS machines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dormitory_id INTEGER REFERENCES dormitories(id) ON DELETE CASCADE DEFAULT 1,
    status SMALLINT DEFAULT 1,
    type_machine VARCHAR(50) NOT NULL,
    number_machine INTEGER
);

CREATE INDEX IF NOT EXISTS idx_machines_status_type ON machines(status, type_machine);
CREATE INDEX IF NOT EXISTS idx_machines_dormitory ON machines(dormitory_id);

-- 5. Таблица бронирований (booking)
-- status: 'Ожидание', 'Ожидание подтверждения', 'Подтверждено', 'Отменено'
CREATE TABLE IF NOT EXISTS booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dormitory_id INTEGER REFERENCES dormitories(id) ON DELETE CASCADE DEFAULT 1,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    inidresidents BIGINT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
    inidmachine INTEGER REFERENCES machines(id) ON DELETE CASCADE,
    status VARCHAR(50) DEFAULT 'Ожидание',
    reminded_tg BOOLEAN DEFAULT FALSE,
    reminded_vk BOOLEAN DEFAULT FALSE,
    reminded_max BOOLEAN DEFAULT FALSE,
    is_autocanceled BOOLEAN DEFAULT FALSE,
    canceled_notified_tg BOOLEAN DEFAULT FALSE,
    canceled_notified_vk BOOLEAN DEFAULT FALSE,
    canceled_notified_max BOOLEAN DEFAULT FALSE,
    finish_notified_tg BOOLEAN DEFAULT FALSE,
    finish_notified_vk BOOLEAN DEFAULT FALSE,
    finish_notified_max BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_booking_machine_time ON booking(inidmachine, start_time, end_time);
CREATE INDEX IF NOT EXISTS idx_booking_residents ON booking(inidresidents);
CREATE INDEX IF NOT EXISTS idx_booking_dormitory ON booking(dormitory_id);
CREATE INDEX IF NOT EXISTS idx_booking_status ON booking(status);

-- 6. Таблица уведомлений (notifications)
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_residents BIGINT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
    id_machines INTEGER REFERENCES machines(id) ON DELETE SET NULL,
    create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT
);

CREATE INDEX IF NOT EXISTS idx_notifications_resident ON notifications(id_residents);

-- 7. Таблица администраторов (administrators)
-- role: 1 = Администратор, 2 = Техник
-- dormitory_id: NULL = главный админ (все общежития), число = привязка к конкретному общежитию
CREATE TABLE IF NOT EXISTS administrators (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role SMALLINT DEFAULT 1,
    dormitory_id INTEGER REFERENCES dormitories(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_administrators_dormitory ON administrators(dormitory_id);

-- 8. Таблица логов входа (login_logs)
CREATE TABLE IF NOT EXISTS login_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER REFERENCES administrators(id) ON DELETE SET NULL,
    success BOOLEAN NOT NULL,
    ip_address VARCHAR(100),
    user_agent TEXT,
    error_message TEXT,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_login_logs_ip_time ON login_logs (ip_address, timestamp);

-- =============================================================================
-- НАЧАЛЬНЫЕ ДАННЫЕ (SEEDS)
-- =============================================================================

-- Общежития КузГТУ
INSERT INTO dormitories (number, name, address) VALUES 
(1, 'Общежитие №1', 'ул. Мичурина, 57'),
(2, 'Общежитие №2', 'ул. Мичурина, 57а'),
(3, 'Общежитие №3', 'ул. Мичурина, 59'),
(4, 'Общежитие №4', 'ул. 50 лет Октября, 17'),
(5, 'Общежитие №5', 'пр. Ленинградский, 30')
ON CONFLICT (number) DO NOTHING;

-- Комнаты
INSERT INTO rooms (idroom) VALUES 
(101), (102), (103), (201), (202), (203), (301), (302), (303), (401), (402), (403)
ON CONFLICT (idroom) DO NOTHING;

-- Учётные записи администраторов и техников (RBAC с разделением по общежитиям)
-- Пароли хранятся в виде криптографических хешей bcrypt (PASSWORD_DEFAULT)
-- Смена пароля доступна через панель управления /change-password
INSERT INTO administrators (username, password_hash, role, dormitory_id) VALUES 
('admin',       '$2y$10$4OkUv6LjKKUvXowc5/9vEuQACU2DDwJ6VxVrtBwSnDodjQnyiqO5i', 1, NULL),
('tech',        '$2y$10$.7aZweoWXigMC14Rjjsn4enOuanr4BntrVmXsDgW4A92yDJkr2brC', 2, NULL),
('admin_dorm3', '$2y$10$tiK4QyTMNfRodxYPXmv9PuQuBjGuBoVS7I1NAURwYK8kldtZt3v.W', 1, 3),
('tech_dorm3',  '$2y$10$OZy/fAjbtJzHUC1Xs3T4AuHU6TRRb5WWGuRHQla.gwj5pOyoVVbGy', 2, 3),
('admin_dorm4', '$2y$10$8z19C24AX8DAs4981GT0l.lGqa2GxGA5/rgvMvl/kq0KcnL5s8DIW', 1, 4),
('tech_dorm4',  '$2y$10$Iw9/ORlyLxKtEiqc7Qgyvup21LliGI3b40p.9GrADWHl.HIjiwCHK', 2, 4),
('admin_dorm1', '$2y$10$/YGnlqiueX/NPGs4Ne1bgueWiXF9sAg5J3PkHIeUFAlLLrx4NDkgG', 1, 1),
('tech_dorm1',  '$2y$10$m8dfotMdJG8M02nVk0E3Sun79CVb4cxXjuwBF4AWnlYqtJ/b4bf6C', 2, 1),
('admin_dorm2', '$2y$10$S.WIkO9DmkeIp5r1ZCcfduQFSIgBXt8W7x/6Ty9m9u0hraWMAi792', 1, 2),
('tech_dorm2',  '$2y$10$puL5lNthiXYg4WvLui4wruo6na9Co7s1zic9lsXZ/UBeO5Tj4Zx86', 2, 2),
('admin_dorm5', '$2y$10$qSSdKcSBEtrNSPZBYWewhekC21QZJ7aZz7dKeVKFXf75/3T9RRZsa', 1, 5),
('tech_dorm5',  '$2y$10$OsZ4VQeaGLGr1W16ac5G5OK16AYHrESyetSK6mmEEO63pdYvRTwOi', 2, 5)
ON CONFLICT (username) DO NOTHING;

-- Машины только для Общежитий №3 и №4
INSERT INTO machines (dormitory_id, type_machine, number_machine, status) VALUES 
-- Общежитие №3
(3, 'Стиральная', 1, 1),
(3, 'Стиральная', 2, 1),
(3, 'Стиральная', 3, 1),
(3, 'Стиральная', 4, 1),
(3, 'Сушильная',  1, 1),
(3, 'Сушильная',  2, 1),
-- Общежитие №4
(4, 'Стиральная', 1, 1),
(4, 'Стиральная', 2, 1),
(4, 'Стиральная', 3, 1),
(4, 'Стиральная', 4, 1),
(4, 'Сушильная',  1, 1),
(4, 'Сушильная',  2, 1)
ON CONFLICT DO NOTHING;

-- Тестовые жильцы (Общежитие №1)
INSERT INTO residents (dormitory_id, last_name, first_name, patronymic, inidroom, idcards, language) VALUES 
(1, 'Иванов', 'Иван', 'Иванович', 101, 123456, 'RU'),
(1, 'Петров', 'Петр', 'Сергеевич', 202, 654321, 'RU')
ON CONFLICT (idcards) DO NOTHING;
