services:
  tgbot:
    build: .
    container_name: layndaru-tgbot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN:-}
      - HOST=${HOST:-postgres}
      - PORT=${PORT:-5432}
      - DBNAME=${DBNAME:-layndaru_db}
      - USER=${USER:-postgres}
      - PASSWORD=${PASSWORD:-postgres}
      - DATABASE_URL=${DATABASE_URL:-}
